### ISSUE TITLE
每次對話需要把紀錄留在資料庫內

### ISSUE THREAD

**Issue by chnbohwr** [bbandydd/ActivityBot#10]
如題 可以討論看看要使用哪種方法

1.  refactor intentHandler 讓它每次收到訊息都寫進資料庫
2. 在express 收到訊息的時候做 middlware 讓它寫入資料庫內

**Comment by chnbohwr** [comment]
跟 @a5081421 討論過以後發現不適合用於 express  middleware 所以會往 intentHandler 部分做實作

這邊還有一個要注意的地方就是每次對話之後要搜尋 db.users 有沒有該使用者，如果沒有的話要把使用者資訊寫入資料庫內，可以再討論看看下面的object 還需要增加哪些東西

```
{
    userId: 'OOOOXXXXXX'  // line user id,
    paymentRecord: []  //記錄繳費狀態陣列
}
```

**Comment by JimmyHou024** [comment]
2017/02/18 完成記錄對話
