### ISSUE TITLE
有人叫 bot 的時候才會回應

### ISSUE THREAD

**Issue by chnbohwr** [bbandydd/ActivityBot#21]
因為怕放到群組裡面以後會一直亂回大家的話

所以想做一個機制就是如果在群組內 `event.source.type === 'group'` 那就要叫名字才會回應

如果是私訊的就直接回應

bot 的名字放在環境變數裡面

[參考資訊](https://devdocs.line.me/en/#webhook-event-object)

**Comment by bbandydd** [comment]
2017/02/19 判斷多人對話需包含bot名字才會執行動作

**Comment by chnbohwr** [comment]
@bbandydd  這邊幫我留意一下大小寫的問題，看要不要都轉成小寫來比對，因為有時候用 iphone 自動輸入的時候第一個字會變成大寫導致判斷錯誤，感恩

**Comment by bbandydd** [comment]
2017/02/20 全以小寫判斷bot name
