### ISSUE TITLE
await 前後請幫忙檢查有沒有用 try catch 包起來

### ISSUE THREAD

**Issue by chnbohwr** [bbandydd/ActivityBot#29]
如題， database 操作的時候如果有錯誤才不會中斷整個程式

請大家幫忙檢查一下各自負責的範圍有沒有遺漏用 try catch 包起來的

感恩

**Comment by bbandydd** [comment]
createActivity.js added try/catch

**Comment by Yang-025** [comment]
joinActivity.js 完成
