### ISSUE TITLE
heroku 不允許 nedb 新增檔案

### ISSUE THREAD

**Issue by chnbohwr** [bbandydd/ActivityBot#41]
### Ephemeral filesystem

Each dyno gets its own ephemeral filesystem, with a fresh copy of the most recently deployed code. During the dyno’s lifetime its running processes can use the filesystem as a temporary scratchpad, **but no files that are written are visible to processes in any other dyno** and any files written will be discarded the moment the dyno is stopped or restarted. For example, this occurs any time a dyno is replaced due to application deployment and approximately once a day as part of normal dyno management.****

我們可能真的要串個 database 了，請大家提供一下意見好了，看看我們要哪種 database ...然後把錢準備好

**Comment by JimmyHou024** [comment]
目前可選擇的資料庫：
1. heroku mongodb
2. google firebase : firebase 可能要定期做 worker 把聊天紀錄搬到 storage 裡面(hyman)
3. mlab
4. heroku mlab

**Comment by chnbohwr** [comment]
經過討論，初步來說，我們要先用 firebase 來做 realtime database 試試看

**Comment by chnbohwr** [comment]
3/5:  先用 mlab mongodb

**Comment by bbandydd** [comment]
2017/03/06  建立活動修改為mongodb
