### ISSUE TITLE
建立活動功能實做

### ISSUE THREAD

**Issue by chnbohwr** [bbandydd/ActivityBot#6]
收到 LUIS 的意圖之後會在 `db.activities` 建立一筆活動

包含的資訊有

日期
地點
活動開始時間
活動結束時間
使用者的 id 列表

**Comment by bbandydd** [comment]
2017/02/17 完成建立活動寫進user.activities

**Comment by chnbohwr** [comment]
補充功能：  建立活動的時候要判斷 user 是不是社長

**Comment by bbandydd** [comment]
2017/02/19 實作社長才可以建立活動
